// Navigation menu items - single source of truth
const menuItems = [
    { href: 'index.html', text: 'Main Page' },
    { href: 'navigation.html', text: 'Navigation Page' },
    { href: 'form-validation.html', text: 'Form Validation' },
    { href: 'data-display.html', text: 'Data Display' },
    { href: 'printing.html', text: 'Printing' },
    { href: 'keyboard-events.html', text: 'Keyboard Events' },
    { href: 'download.html', text: 'Download' },
    { href: '#', text: 'Logout', onclick: 'logout(); return false;' }
];

// Generate menu HTML
function generateMenuHTML() {
    return menuItems.map(item => {
        if (item.onclick) {
            return `<a href="${item.href}" onclick="${item.onclick}">${item.text}</a>`;
        }
        return `<a href="${item.href}">${item.text}</a>`;
    }).join('');
}

// Initialize hamburger menu structure (injects HTML and sets up event listeners)
function initializeHamburgerMenu() {
    // Check if hamburger menu already exists
    if (document.getElementById('hamburger-menu')) {
        return;
    }

    // Create hamburger menu HTML
    const hamburgerMenuHTML = `
        <div class="hamburger-menu" id="hamburger-menu">
            <button class="hamburger-btn" id="hamburger-btn" aria-label="Toggle menu">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <div class="username-display" id="username-display"></div>
            <nav class="menu-nav" id="menu-nav">
                <!-- Menu items will be generated by menu.js -->
            </nav>
        </div>
    `;

    // Insert at the beginning of body
    document.body.insertAdjacentHTML('afterbegin', hamburgerMenuHTML);

    // Initialize menu items
    const menuNav = document.getElementById('menu-nav');
    if (menuNav) {
        menuNav.innerHTML = generateMenuHTML();
    }

    // Set up hamburger menu functionality
    const hamburgerBtn = document.getElementById('hamburger-btn');
    
    if (hamburgerBtn && menuNav) {
        hamburgerBtn.addEventListener('click', function() {
            menuNav.classList.toggle('active');
        });

        // Close menu when clicking outside
        document.addEventListener('click', function(event) {
            const isClickInsideMenu = menuNav.contains(event.target);
            const isClickOnButton = hamburgerBtn.contains(event.target);
            
            if (!isClickInsideMenu && !isClickOnButton && menuNav.classList.contains('active')) {
                menuNav.classList.remove('active');
            }
        });
    }

    // Display username if auth.js is loaded and user is authenticated
    if (typeof displayUsername === 'function') {
        displayUsername();
    }
}

// Auto-initialize when script loads (if DOM is ready)
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initializeHamburgerMenu);
} else {
    initializeHamburgerMenu();
}
